---
- name: dependency provisioning
  hosts: all
  gather_facts: false
  tasks:
    - name: install python2
      become: yes
      become_method: sudo
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  name: Start Mongo Server
  gather_facts: true
  vars: 
    BIND_IP: "0.0.0.0"
  tasks:
    - include: mongo.yml
    
    - name: accept all ips (BAD in production, specify correct server ip!!
      become: yes
      become_method: sudo
      command: "sed -i 's/127.0.0.1/{{ BIND_IP }}/' /etc/mongod.conf"
    - name: Restart daemon
      become: yes
      become_method: sudo
      service:
         name: mongod
         state: restarted
