---
- hosts: azure
  vars:
    go_dir: "/usr/local/go/bin"
    go_home_dir: "{{ lookup('env','HOME') }}/go"
    project_dir: "{{ go_home_dir }}/src/github.com/alex1ai/ugr-master-cc"
    port_nr: 3000
  environment:
    PORT: "{{ port_nr }}"
    IP: "0.0.0.0"
  tasks:
  - name: Update packages
    become: true
    become_method: sudo
    apt: update_cache=yes

  - name: Install Git
    become: true
    become_method: sudo
    apt: pkg=git state=present

  - name: Download and extract Go
    become: true
    become_method: sudo
    unarchive:
      src: https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
      dest: /usr/local/
      remote_src: yes
      creates: /usr/local/go

  - name: Create Source Path for Github-Project
    file:
      path: "{{ project_dir }}"
      state: directory
      mode: 0755

  - name: Clone Repository from Github into Go-Directory
    git:
      repo: 'https://github.com/alex1ai/ugr-master-cc.git'
      dest: "{{ project_dir }}"

  - name: Add Go-binary to environment
    become: true
    become_method: sudo
    file:
      dest: '/usr/bin/go'
      src: '{{ go_dir }}/go'
      state: link

  - name: "Add Portforwarding from 80 to {{ port_nr }}"
    become: true
    become_method: sudo
    command: "iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports {{ port_nr }}"

  - name: Get dependencies for project
    shell:
      cmd: "go get -d"
      chdir: "{{ project_dir }}"

  - name: Install project
    shell:
      cmd: "go install"
      chdir: "{{ project_dir }}"

  - name: Run webservice in different process
    shell: "{{ go_home_dir }}/bin/ugr-master-cc > /tmp/log.log &"
