version: '3'
services:
  data:
    image: mongo
    restart: always
    command: --smallfiles
  web:
    build: .
    env_file:
      - secrets.env
    environment:
      - MONGO_IP=data
    ports:
      - "80:3000"