version: '3'
services:
  data:
    image: mongo
    restart: always
    command: --smallfiles
    ports:
      - "27017:27017"
  web:
    depends_on:
      - data
    image: alexgrimm/infogration-backend
    env_file:
      - secrets.env
    environment:
      MONGO_IP: data
    ports:
      - "80:3000"
    restart: always
