# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "ubuntu/xenial64"
BASE_IP = "192.168.50.1"
IP_DATA = "192.168.50.2"
IP_SERVER = "192.168.50.3"

Vagrant.configure("2") do |config|

  config.vm.define 'data' do |data|
    data.vm.box = BOX
    data.vm.provision "ansible" do |ansible|
		ansible.playbook = "./provision/data_playbook.yml"
	end
	data.vm.network "private_network", ip: IP_DATA
  end

  config.vm.define 'server' do |local|	
	local.vm.box = BOX
    local.vm.provision "ansible" do |ansible|
        ansible.playbook = "./provision/playbook.yml"
    end
	local.vm.network "private_network", ip: IP_SERVER 
    local.vm.network "forwarded_port", guest:3000, host:4321  
  end

end
