# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-azure'
# Azure information
TENANT_ID = ENV['AZURE_TENANT_ID']
CLIENT_ID = ENV['AZURE_CLIENT_ID']
CLIENT_SECRET = ENV['AZURE_CLIENT_SECRET']
SUBSCRIPTION_ID = ENV['AZURE_SUBSCRIPTION_ID']

# VM specification
VM_SIZE="Standard_B1s"
LOCATION="francecentral"
RESOURCE_GROUP="vagrant"
NAME="vagrant-server"

Vagrant.configure("2") do |config|
    config.vm.define 'server' do |server|
        server.vm.box = 'azure'
        server.vm.provider :azure do |az, override|
            az.tenant_id = TENANT_ID 
            az.client_id = CLIENT_ID
            az.client_secret = CLIENT_SECRET
            az.subscription_id = SUBSCRIPTION_ID

			az.vm_name = NAME
            az.vm_size = VM_SIZE

            # az.vm_image_urn = "canonical:ubuntuserver:16.04-LTS:latest"
            az.tcp_endpoints = 80
            az.location = LOCATION
            az.resource_group_name = RESOURCE_GROUP
        end

        server.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "./provision/playbook.yml"
        end
    end
    config.ssh.private_key_path = '~/.ssh/id_rsa'
end
